Inital work
SverigesSandareamatorer/SSA-Akademin pull request #546
Opened 2021-11-29 09:18 UTC by k7per

Detta är den första pull request för de ändringar vi har pratat om tillsammans i den två senaste mötena.

2021-11-29 10:13 UTC, phieri requested changes
Fantastiskt arbete!

Några saker har jag hittat. Kommentarerna gäller för alla liknande ställen.

2021-11-29 10:13 UTC, phieri commented on koncept/chapter13-4.tex
> +\index{NÖDANROP}
"nödanrop" finns redan med någon rad upp.

2021-11-29 10:13 UTC, phieri commented on koncept/chapter2-2.tex
> +%% k7per: Definiera "glimmer".
Den här sortens kommentar skulle jag gärna hålla borta från koden. Öppna hellre ett ärende på GitHub och referera till kodraden.

2021-11-29 10:13 UTC, phieri commented on koncept/chapter3-1.tex
> +som laddningsströmmen sjunker från \(I_{\it max}\) till 0~ampere.  Spänningen
Flytta ner `Spänningen` till nästa kodrad.

2021-11-29 10:13 UTC, phieri commented on koncept/chapter7-1.tex
> +för att det inte ska uppstå vågreflektion i anslutningen.
Jag tror att "reflexion" är det bättre alternativet. Se _Svensk Ordbok_ https://svenska.se/so/?id=165484&pz=7

2021-11-29 10:13 UTC, phieri commented on koncept/foreword.tex
> +och vi har försökt att göra texten enklare och bättre att läsa, tex
t.ex. istället för tex.

2021-11-29 10:56 UTC, k7per commented
Tack!

Nedan.

On Mon, Nov 29, 2021 at 11:13 AM Philip Eriksson ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Fantastiskt arbete!
>
> Några saker har jag hittat. Kommentarerna gäller för alla liknande ställen.
> ------------------------------
>
> In koncept/chapter11-1.tex
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r758197942&data=04%7C01%7C%7C8f88ab1813434f215f5108d9b320ec1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737776241452614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=evBablsqHJ8Zho6lMMcpl5k916jcEaB2YP2w851bMaM%3D&reserved=0>
> :
>
> > @@ -94,7 +94,7 @@ \section{Fält}
>
>  kallar fjärrfältet, längre bort från antennen och närfältet nära antennen.
>
>
>
>  \index{fjärrfält}
>
> -I fjärrfältet kan man på grund av växelverkan mellan det elektriska- och det
>
> +I fjärrfältet kan man tack vara växelverkan mellan det elektriska- och det
>
>
> Stavfel.
>

fixat.


> ------------------------------
>
> In koncept/chapter12-3.tex
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r758199247&data=04%7C01%7C%7C8f88ab1813434f215f5108d9b320ec1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737776241452614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XBjz%2BPgUeRJeODM5KhRn2lDiKTUYzi0%2Fa6KvPsnhogw%3D&reserved=0>
> :
>
> > @@ -159,8 +159,8 @@ \subsection{Säkerhetsåtgärder}
>
>  \begin{itemize}
>
>  \item Arbeta inte med anläggningen när du är trött eller omotiverad.
>
>    Då är du minst vaksam mot olyckor.
>
> -\item Se till att du inte får ström genom kroppen, arbeta helst bara med höger
>
> -  hand och håll den andra borta från den utrustning som du arbetar med.
>
> +\item Se till att du inte får ström genom kroppen, arbeta helst bara med ena
>
> +  handen och håll den andra borta från den utrustning som du arbetar med.
>
>
> Den här skulle jag gärna ta en separat diskussion om. Förklaringen jag
> hört är ju att hjärtat sitter på vänster sida, men om det någonsin haft
> någon betydelse har jag ingen aning om.
>
Hmm, bra.  I så fall tror jag att vi ska lägga till det, efter lite
forskning, så att det inte framstår som vi högerhänta vinner...


> ------------------------------
>
> In koncept/chapter13-4.tex
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r758200624&data=04%7C01%7C%7C8f88ab1813434f215f5108d9b320ec1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737776241462607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EdqdGhATIOPsH0QQXSMqnguJKX6WpHbjhUUWWSJ0tc0%3D&reserved=0>
> :
>
> >
>
>  \subsection{Nödsignaler}
>
>  \label{nödsignaler}
>
>  \index{nödsignaler}
>
>  \index{nödanrop}
>
>  \index{SOS}
>
>  \index{MAYDAY}
>
> +\index{NÖDANROP}
>
>
> "nödanrop" finns redan med någon rad upp.
>

Ops, fixat.


> ------------------------------
>
> In koncept/chapter2-2.tex
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r758202938&data=04%7C01%7C%7C8f88ab1813434f215f5108d9b320ec1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737776241462607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5l9mEUIagUR7FgKt3cS1l1KhTTUq05k%2F3d%2FanIc0aHg%3D&reserved=0>
> :
>
> > @@ -216,6 +216,7 @@ \subsection{Läckström}
>
>  \subsection{Utförandeformer}
>
>
>
>  Kondensatorer kan utföras med fast kapacitansvärde.
>
> +%% k7per: Definiera "glimmer".
>
>
> Den här sortens kommentar skulle jag gärna hålla borta från koden. Öppna
> hellre ett ärende på GitHub och referera till kodraden.
>

Bra, under de kommande veckorna ska jag ta bort alla mina k7per kommentarer
och lägga in dem i github, också det som finns i filen k7per.text som inte
är klart.


> ------------------------------
>
> In koncept/chapter3-1.tex
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r758204860&data=04%7C01%7C%7C8f88ab1813434f215f5108d9b320ec1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737776241472601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X65Y%2B4eFaGxAJMMdmM3KjZDDOHY8wACwjNJ6Vu%2BbJIE%3D&reserved=0>
> :
>
> > @@ -364,20 +360,18 @@ \subsubsection{Uppladdning}
>
>
>
>  % PHU: Bilden förvirrar. U i kretsschemat är samma som U_max i diagrammet.
>
>
>
> -Spänningen över kondensatorn stiger från 0~volt till \(U_{\it max}\).
>
> -
>
> -Laddningsströmmen sjunker från \(I_{\it max}\) till 0~ampere.
>
> -
>
> -Spänningen över kondensatorn ökar exponentiellt under uppladdningen.
>
> +Spänningen över kondensatorn stiger från 0~volt till \(U_{\it max}\) samtidigt
>
> +som laddningsströmmen sjunker från \(I_{\it max}\) till 0~ampere.  Spänningen
>
>
> Flytta ner Spänningen till nästa kodrad.
>

Menar du för att få ett nytt stycke?


> ------------------------------
>
> In koncept/chapter7-1.tex
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r758211199&data=04%7C01%7C%7C8f88ab1813434f215f5108d9b320ec1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737776241472601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bCG%2FSrogAIOCWBE%2BAo%2Fhn4H%2BPr3jLpsgVw2WjjLhE8M%3D&reserved=0>
> :
>
> > @@ -190,7 +190,7 @@ \subsection{Impedansen i antennens matningspunkt}
>
>  I praktiken kan impedansen avvika mycket från detta värde.
>
>
>
>  Antenn och matningskabel måste vara impedansanpassade till varandra
>
> -för att det inte ska uppstå vågreflexion i anslutningen.
>
> +för att det inte ska uppstå vågreflektion i anslutningen.
>
>
> Jag tror att "reflexion" är det bättre alternativet. Se *Svensk Ordbok*
> https://svenska.se/so/?id=165484&pz=7
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsvenska.se%2Fso%2F%3Fid%3D165484%26pz%3D7&data=04%7C01%7C%7C8f88ab1813434f215f5108d9b320ec1a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737776241482598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ziI5t5TgU7%2Bruoq%2FRogzMzj6IhJ45nuuLUAbe68KQ7k%3D&reserved=0>
>

Vi diskuterade detta i mötet innan det du var med i, och vi sa att
reflexion var bättre, men när jag kollade på texten så är det många ord med
refle* som borde vara konsekventa.

Jag har ingen speciell åsikt här, om vi tycker det är bäst med reflexion i
alla ord nedan, så fixar jag det.

Ska Aurora( vara sammanskrivet eller med bindestreck?

Hampuss-2013-MacBook-Pro:koncept perham$ fgrep -i reflektion *.tex

appendix-o.tex:\ref{vågutbredning_reflektion},
\ref{vågutbredning_jonosfärskikten}--

chapter1-8.tex:*meteorreflektioner* på \SI{6}{\metre}-bandet.

chapter7-1.tex:för att det inte ska uppstå *vågreflektion* i anslutningen.

chapter8-2.tex:  \item upp från jordytan efter en första *reflektion* mot
denna.

chapter8-2.tex:  \item reflektion eller splittring mot naturliga
*reflektorer* i

chapter8-2.tex:En antenns höjd påverkar riktningen av vågen, på grund av
reflektion mot

chapter8-2.tex:och den riktning där *reflektionen* samverkar med en, eller
flera, hel våglängds

chapter8-2.tex:\subsubsection{Reflektion}

chapter8-2.tex:\index{radiovågor!reflektion}

chapter8-2.tex:\label{vågutbredning_reflektion}

chapter8-2.tex:Reflektion innebär att vågorna böjs tillbaka från den yta
som de träffar.

chapter8-3.tex:D-skiktet har dålig *reflektionsförmåga* och verkar
hindrande på

chapter8-3.tex:Ett säsongmaximum i *reflektions [...]

2021-11-29 10:57 UTC, k7per commented on koncept/foreword.tex
> +och vi har försökt att göra texten enklare och bättre att läsa, tex
fixat.

2021-11-29 10:58 UTC, k7per commented on koncept/chapter11-1.tex
> +I fjärrfältet kan man tack vara växelverkan mellan det elektriska- och det
Fixat

2021-11-29 10:58 UTC, k7per commented on koncept/chapter12-3.tex
> +  handen och håll den andra borta från den utrustning som du arbetar med.
Hmm, bra.  I så fall tror jag att vi ska lägga till det, efter lite forskning, så att det inte framstår som vi högerhänta vinner...

2021-11-29 10:59 UTC, k7per commented on koncept/chapter13-4.tex
> +\index{NÖDANROP}
fixat.

2021-11-29 10:59 UTC, k7per commented on koncept/chapter3-1.tex
> +som laddningsströmmen sjunker från \(I_{\it max}\) till 0~ampere.  Spänningen
Vill du ha en nytt styckle?

2021-11-29 11:00 UTC, k7per commented on koncept/chapter7-1.tex
> +för att det inte ska uppstå vågreflektion i anslutningen.
Vi diskuterade detta i mötet innan det du var med i, och vi sa att reflexion var bättre, men när jag kollade på texten så är det många ord med refle* som borde vara konsekventa.

Jag har ingen speciell åsikt här, om vi tycker det är bäst med reflexion i alla ord nedan, så fixar jag det.

Ska Aurora( vara sammanskrivet eller med bindestreck?

Hampuss-2013-MacBook-Pro:koncept perham$ fgrep -i reflektion *.tex

appendix-o.tex:\ref{vågutbredning_reflektion}, \ref{vågutbredning_jonosfärskikten}--

chapter1-8.tex:meteorreflektioner på \SI{6}{\metre}-bandet.

chapter7-1.tex:för att det inte ska uppstå vågreflektion i anslutningen.

chapter8-2.tex:  \item upp från jordytan efter en första reflektion mot denna.

chapter8-2.tex:  \item reflektion eller splittring mot naturliga reflektorer i

chapter8-2.tex:En antenns höjd påverkar riktningen av vågen, på grund av reflektion mot

chapter8-2.tex:och den riktning där reflektionen samverkar med en, eller flera, hel våglängds

chapter8-2.tex:\subsubsection{Reflektion}

chapter8-2.tex:\index{radiovågor!reflektion}

chapter8-2.tex:\label{vågutbredning_reflektion}

chapter8-2.tex:Reflektion innebär att vågorna böjs tillbaka från den yta som de träffar.

chapter8-3.tex:D-skiktet har dålig reflektionsförmåga och verkar hindrande på

chapter8-3.tex:Ett säsongmaximum i reflektionsförmågan inträffar under sommaren.

chapter8-3.tex:joniseringsgrad och stor reflektionsförmåga, det så kallade \emph{sporadiska

chapter8-3.tex:Reflektioner i \(\mathrm{F_2}\)-skiktet möjliggör att stora

chapter8-3.tex:Vid en viss övre frekvens upphör reflektionen i atmosfärskiktet och

chapter8-5.tex:kontakt med atmosfären genom reflektion eller refraktion.

chapter8-5.tex:För att bäst uppnå den önskade reflektionen måste man dels välja

chapter8-5.tex:reflektioner mellan jordytan och jonosfären.

chapter8-5.tex:Vågutbredningen sker då både genom refraktion i D-skiktet och reflektion i

chapter8-5.tex:\item vågutbredningsriktningen ändras genom reflektioner mot hus,

chapter8-5.tex:  bergväggar etc. (reflektionsförluster, vid t.ex. mobil radiotrafik).

chapter8-5.tex:Kommunikation upp till \SI{3000}{\kilo\metre} via \(F_2\) reflektion är i

chapter8-5.tex:Bandet är dött nattetid. Vid reflektioner via sporadiskt E-skikt kan avstånd av

chapter8-5.tex:möjliga genom reflektioner via sporadiska E-skikt (short skip).

chapter8-6.tex:\subsection{Reflektion mot E\raisebox{-.4ex}{s} (sporadiskt E)}

chapter8-6.tex:\subsection{Aurora-reflektion}

chapter8-6.tex:VHF- och UHF-kommunikation kan ske med hjälp av aurorareflektion.

chapter8-6.tex:\subsection{Reflektion mot meteorer -- Meteorscatter}

chapter8-6.tex:genom reflektion av VHF-/UHF-signaler mot månen.

Hampuss-2013-MacBook-Pro:koncept perham$

2021-11-29 11:03 UTC, k7per commented on koncept/chapter2-2.tex
> +%% k7per: Definiera "glimmer".
Bra. Jag ska flytta alla kommentarer och kvarvarande innehåll i filen k7per.text.

2021-11-29 11:05 UTC, phieri commented on koncept/chapter3-1.tex
> +som laddningsströmmen sjunker från \(I_{\it max}\) till 0~ampere.  Spänningen
Nej, bara att ny mening börjar på egen rad i koden. Ingen förändring i den byggda PDF:en.

2021-11-29 11:11 UTC, k7per commented on koncept/chapter3-1.tex
> +som laddningsströmmen sjunker från \(I_{\it max}\) till 0~ampere.  Spänningen
fixat.

2021-11-29 19:34 UTC, SM7NTJ commented on koncept/chapter12-3.tex
> +  handen och håll den andra borta från den utrustning som du arbetar med.
Att bara jobba med höger hand är en gammal kvarleva som egentligen inte har ett renodlat vetenskapligt stöd. Det viktiga är att bara jobba på ett sådant sätt att man undviker strömgenomgång. Så formuleringen bara ena handen är bra och neutral då den inte tvingar vänsterhänta att jobba med fel hand.
Skadeverkan vid strömgenomgång bestäms av en rad faktorer där de vanligaste brukar anges som strömmen storlek, strömmens väg genom kroppen och tiden.
Mer finns att läsa här http://www.internetmedicin.se/page.aspx?id=5851

2021-11-29 19:43 UTC, SM7NTJ commented on koncept/chapter7-1.tex
> +för att det inte ska uppstå vågreflektion i anslutningen.
Ja vi sa att reflexion är mera riktigt i merparten av fallen.

2021-11-29 19:48 UTC, SM7NTJ approved these changes
Bra jobb.

2021-11-30 21:25 UTC, sm5phu commented on koncept/chapter7-1.tex
> +för att det inte ska uppstå vågreflektion i anslutningen.
Nu har jag kollat med min gode vän, den pensionerade svenskläraren. Om det finns någon betydelseskillnad, så menar han att vi borde välja "reflektion" i det här sammanhanget. Så jag ändrar mig och röstar för "reflektion".

Och jag föredrar "aurorareflektion" framför "aurora-reflektion". (Men på svenska heter det "norrsken"...)

2021-11-30 21:37 UTC, sm5phu approved these changes

2021-12-01 04:41 UTC, SM7NTJ commented on koncept/chapter7-1.tex
> +för att det inte ska uppstå vågreflektion i anslutningen.
Svenska kan vara krångligt. Så även i det här fallet. Jag kan tänka mig att låta reflektion stå kvar så att vi inte av misstag missar och råkar byta ut reflektor mot ... i antennavsnittet ;=)

2021-12-01 07:30 UTC, k7per commented
Ok, om det inte finns några andra protester så låter vi det stå.

Varför inte skriva norrsken då? Med aurora inom parentes för att koppla
till andra språk.

On Tue, Nov 30, 2021 at 22:25 sm5phu ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In koncept/chapter7-1.tex
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r759671784&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429086015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=t0yOgCSQrv84iqtu%2FWp49C5FPLbzJ8TgVFC%2FQrBZQn4%3D&reserved=0>
> :
>
> > @@ -190,7 +190,7 @@ \subsection{Impedansen i antennens matningspunkt}
>
>  I praktiken kan impedansen avvika mycket från detta värde.
>
>
>
>  Antenn och matningskabel måste vara impedansanpassade till varandra
>
> -för att det inte ska uppstå vågreflexion i anslutningen.
>
> +för att det inte ska uppstå vågreflektion i anslutningen.
>
>
> Nu har jag kollat med min gode vän, den pensionerade svenskläraren. Om det
> finns någon betydelseskillnad, så menar han att vi borde välja "reflektion"
> i det här sammanhanget. Så jag ändrar mig och röstar för "reflektion".
>
> Och jag föredrar "aurorareflektion" framför "aurora-reflektion". (Men på
> svenska heter det "norrsken"...)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r759671784&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429096011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Yb9HlEFFGeEV0jD2PCfdzmfUfA7GwqxyBszlIKiz%2BGs%3D&reserved=0>,
> or unsubscribe
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWOAPQFI4HJFMPDFVLTG2JDUOU6NJANCNFSM5I6TTFJQ&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aPf5MFaBsNDTv%2BQEajJoJ3li3L3R%2BjkLJQTYCFtzwGM%3D&reserved=0>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aAARCRabP0an18DmuDlfBu%2BB%2FKVNMhBxDzx1rQT8eJs%3D&reserved=0>
> or Android
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mn62L2XA1Icprt6czvE%2BCMW55HZ5TSy2BAXDaIW%2BwfQ%3D&reserved=0>.
>
>

2021-12-01 16:22 UTC, sikvall commented
Aurora är det begrepp som används inom amatörradio mest.
Det kan lika gärna vara sydsken (Aurora Australis) som norrsken (Aurora
Borealis)

Mvh,
*Täpp Anders*



Den ons 1 dec. 2021 kl 08:30 skrev k7per ***@***.***>:

> Ok, om det inte finns några andra protester så låter vi det stå.
>
> Varför inte skriva norrsken då? Med aurora inom parentes för att koppla
> till andra språk.
>
> On Tue, Nov 30, 2021 at 22:25 sm5phu ***@***.***> wrote:
>
> > ***@***.**** commented on this pull request.
> > ------------------------------
> >
> > In koncept/chapter7-1.tex
> > <
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r759671784&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429086015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=t0yOgCSQrv84iqtu%2FWp49C5FPLbzJ8TgVFC%2FQrBZQn4%3D&reserved=0
> >
> > :
> >
> > > @@ -190,7 +190,7 @@ \subsection{Impedansen i antennens matningspunkt}
> >
> > I praktiken kan impedansen avvika mycket från detta värde.
> >
> >
> >
> > Antenn och matningskabel måste vara impedansanpassade till varandra
> >
> > -för att det inte ska uppstå vågreflexion i anslutningen.
> >
> > +för att det inte ska uppstå vågreflektion i anslutningen.
> >
> >
> > Nu har jag kollat med min gode vän, den pensionerade svenskläraren. Om
> det
> > finns någon betydelseskillnad, så menar han att vi borde välja
> "reflektion"
> > i det här sammanhanget. Så jag ändrar mig och röstar för "reflektion".
> >
> > Och jag föredrar "aurorareflektion" framför "aurora-reflektion". (Men på
> > svenska heter det "norrsken"...)
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r759671784&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429096011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Yb9HlEFFGeEV0jD2PCfdzmfUfA7GwqxyBszlIKiz%2BGs%3D&reserved=0
> >,
> > or unsubscribe
> > <
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWOAPQFI4HJFMPDFVLTG2JDUOU6NJANCNFSM5I6TTFJQ&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aPf5MFaBsNDTv%2BQEajJoJ3li3L3R%2BjkLJQTYCFtzwGM%3D&reserved=0
> >
> > .
> > Triage notifications on the go with GitHub Mobile for iOS
> > <
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aAARCRabP0an18DmuDlfBu%2BB%2FKVNMhBxDzx1rQT8eJs%3D&reserved=0
> >
> > or Android
> > <
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mn62L2XA1Icprt6czvE%2BCMW55HZ5TSy2BAXDaIW%2BwfQ%3D&reserved=0
> >.
> >
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SverigesSandareamatorer/SSA-Akademin/pull/546#issuecomment-983365749>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC5IZMUDVIAP3AK5E7XA2XLUOXFKBANCNFSM5I6TTFJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-01 16:32 UTC, k7per commented
Ja, jag tänkte på det efter jag skrev det...

per


On Wed, Dec 1, 2021 at 5:22 PM Anders Sikvall ***@***.***>
wrote:

> Aurora är det begrepp som används inom amatörradio mest.
> Det kan lika gärna vara sydsken (Aurora Australis) som norrsken (Aurora
> Borealis)
>
> Mvh,
> *Täpp Anders*
>
>
>
> Den ons 1 dec. 2021 kl 08:30 skrev k7per ***@***.***>:
>
> > Ok, om det inte finns några andra protester så låter vi det stå.
> >
> > Varför inte skriva norrsken då? Med aurora inom parentes för att koppla
> > till andra språk.
> >
> > On Tue, Nov 30, 2021 at 22:25 sm5phu ***@***.***> wrote:
> >
> > > ***@***.**** commented on this pull request.
> > > ------------------------------
> > >
> > > In koncept/chapter7-1.tex
> > > <
> >
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r759671784&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429086015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=t0yOgCSQrv84iqtu%2FWp49C5FPLbzJ8TgVFC%2FQrBZQn4%3D&reserved=0
> > >
> > > :
> > >
> > > > @@ -190,7 +190,7 @@ \subsection{Impedansen i antennens matningspunkt}
> > >
> > > I praktiken kan impedansen avvika mycket från detta värde.
> > >
> > >
> > >
> > > Antenn och matningskabel måste vara impedansanpassade till varandra
> > >
> > > -för att det inte ska uppstå vågreflexion i anslutningen.
> > >
> > > +för att det inte ska uppstå vågreflektion i anslutningen.
> > >
> > >
> > > Nu har jag kollat med min gode vän, den pensionerade svenskläraren. Om
> > det
> > > finns någon betydelseskillnad, så menar han att vi borde välja
> > "reflektion"
> > > i det här sammanhanget. Så jag ändrar mig och röstar för "reflektion".
> > >
> > > Och jag föredrar "aurorareflektion" framför "aurora-reflektion". (Men
> på
> > > svenska heter det "norrsken"...)
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23discussion_r759671784&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429096011%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Yb9HlEFFGeEV0jD2PCfdzmfUfA7GwqxyBszlIKiz%2BGs%3D&reserved=0
> > >,
> > > or unsubscribe
> > > <
> >
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWOAPQFI4HJFMPDFVLTG2JDUOU6NJANCNFSM5I6TTFJQ&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aPf5MFaBsNDTv%2BQEajJoJ3li3L3R%2BjkLJQTYCFtzwGM%3D&reserved=0
> > >
> > > .
> > > Triage notifications on the go with GitHub Mobile for iOS
> > > <
> >
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aAARCRabP0an18DmuDlfBu%2BB%2FKVNMhBxDzx1rQT8eJs%3D&reserved=0
> > >
> > > or Android
> > > <
> >
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C940039cb66a14b07047908d9b447f5f7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739043429106002%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mn62L2XA1Icprt6czvE%2BCMW55HZ5TSy2BAXDaIW%2BwfQ%3D&reserved=0
> > >.
> > >
> > >
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/SverigesSandareamatorer/SSA-Akademin/pull/546#issuecomment-983365749
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AC5IZMUDVIAP3AK5E7XA2XLUOXFKBANCNFSM5I6TTFJQ
> >
> > .
> > Triage notifications on the go with GitHub Mobile for iOS
> > <
> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675
> >
> > or Android
> > <
> https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub
> >.
> >
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F546%23issuecomment-983807328&data=04%7C01%7C%7C5ea6eeff7f3d4999eb2208d9b4e6d395%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739725751433728%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fdgf3Fsp1WeH8gAsV%2F4UlWHXrxr3Ci6ajV3QfMlEm8c%3D&reserved=0>,
> or unsubscribe
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWOAPQFJT3BSLADWG4AOMH3UOZDV3ANCNFSM5I6TTFJQ&data=04%7C01%7C%7C5ea6eeff7f3d4999eb2208d9b4e6d395%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739725751443726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ci2oEJpKtBGJfixlg%2BzYlPuOcmnru9KUpfcoHMJFCFs%3D&reserved=0>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C5ea6eeff7f3d4999eb2208d9b4e6d395%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739725751453711%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QVRU8z8cE5VdpkepaX4iipOIoHS0praPqfqyLI1Yp08%3D&reserved=0>
> or Android
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C5ea6eeff7f3d4999eb2208d9b4e6d395%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637739725751453711%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WO5mY1%2BTfrSCuFofEvcAMFn2do%2BRBw3DtkH9YIsfxVQ%3D&reserved=0>.
>
>

2021-12-02 12:07 UTC, phieri commented
Jag slänger in _polarsken_ i debatten också.

2021-12-02 12:46 UTC, sikvall commented
Hej!

Det kan man absolut ha med sig. Man kan ju ha ett stycke som förklarar att
just *aurora* är ett begrepp som betyder polarsken eller norr- och sydsken
och att bland radioamatörer är det ofta just begreppet aurora som används.

Jag vill alltså inte att vi byter ut begreppet eftersom det är så väl
etablerat i amatörradiocommunityn, men tycker att vi gärna kan ta med de
andra begreppen som förklaring så folk som är nya och läser till cert
förstår vad det handlar om.

Mvh,
*Täpp Anders*



Den tors 2 dec. 2021 kl 13:07 skrev Philip Eriksson <
***@***.***>:

> Jag slänger in *polarsken* i debatten också.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/SverigesSandareamatorer/SSA-Akademin/pull/546#issuecomment-984567657>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC5IZMUHDAOX6NWDEVOBDUTUO5OPPANCNFSM5I6TTFJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-03 07:09 UTC, k7per commented on koncept/chapter7-1.tex
> +för att det inte ska uppstå vågreflektion i anslutningen.
Jag bytte två andra reflex-liknande ord i chapter1-9 och chapter4-1, så nu är hela texten förhoppningsvis enhetlig.  Tog bort bindestreck i aurora-reflektion.

Jag kollade texten om "norrsken" och jag tycker den verkar bra.

Kolla är ni snälla, är det OK nu?

2021-12-04 19:45 UTC, k7per commented on koncept/chapter7-1.tex
> +för att det inte ska uppstå vågreflektion i anslutningen.
Är vi klara här, alla OK med reflektion?

2021-12-04 19:46 UTC, k7per commented on koncept/chapter14-3.tex
> +av 12\S  förordningen (2003:396) \cite{SFS2003:396} om elektronisk kommunikation
OK. Fixade till med mellenslag efter 12$.

2021-12-07 17:42 UTC, phieri requested changes
Det har kommit med en macOS-systemfil i images/cropped_pdfs/.DS_Store som inte ska vara med.

2021-12-07 20:02 UTC, phieri commented on koncept-tryck.tex
> +\hyphenation{amatör-radio-sändaren MAY-DAY mo-du-ler-ing för-utom elektronrörs-epoken frekvens-karaktäristiken radio-vågor materie-formerna tantal-elek-tro-lyt-kondensatorer halv-led-ar-ele-ment seri
Det finns redan en lista på avstavningar i common.tex.

2021-12-09 18:08 UTC, merged