#559
SverigesSandareamatorer/SSA-Akademin pull request #577
Opened 2022-01-02 14:25 UTC by k7per

Created a sample Octave file for your enjoyment.

Please take a look and see what you think.

The result is far from perfect, I need to follow up on national characters and also on why the stipple pattern appears to be dependent on the resolution of the calculation...

### Innehåll

- Förändringar

### Checklista

- [ ] Följer stilmallen specificerad i [`CONTRIBUTING.md`](../blob/master/.github/CONTRIBUTING.md)
- [ ] Språkligt granskad (stavning och grammatik)
- [ ] Förändringar bygger utan fel lokalt
- [ ] Förändringar bygger utan fel på byggserver
- [ ] Förändringar (om signifikanta) införd i [`CHANGELOG.md`](../blob/master/CHANGELOG.md)
- [ ] Godkänd av två granskare
- [ ] Författaren är klar och godkänner merge

### Stänger följande issues

Fixes # `<- följt av issue-nummer`

2022-01-07 15:14 UTC, phieri requested changes
Ta bort den gamla filen med den här PR:n så vi håller filträdet städat.

2022-01-18 14:10 UTC, k7per commented
Jag tog port de 3 gamla power.{mac, png, pdf} filerna.

2022-01-19 20:17 UTC, SM7NTJ approved these changes
Ok bilden är nu lättare att tyda vid tryckning i svartvitt

2022-01-21 18:27 UTC, phieri commented
Skulle du kunna skriva en rad i CHANGELOG.md om att det är fixat?

2022-01-26 18:02 UTC, merged