Final massage
SverigesSandareamatorer/SSA-Akademin pull request #585
Opened 2022-01-11 07:37 UTC by k7per

### Innehåll

- Förändringar

### Checklista

- [ ] Följer stilmallen specificerad i [`CONTRIBUTING.md`](../blob/master/.github/CONTRIBUTING.md)
- [ ] Språkligt granskad (stavning och grammatik)
- [ ] Förändringar bygger utan fel lokalt
- [ ] Förändringar bygger utan fel på byggserver
- [ ] Förändringar (om signifikanta) införd i [`CHANGELOG.md`](../blob/master/CHANGELOG.md)
- [ ] Godkänd av två granskare
- [ ] Författaren är klar och godkänner merge

### Stänger följande issues

Fixes # `<- följt av issue-nummer`

2022-01-13 11:32 UTC, phieri requested changes

2022-01-13 11:32 UTC, phieri commented on koncept/appendix-mattenheter.tex
> +tekniska begrepp.  Märk att samma symboler används olika inom olika
Börja ny mening på ny rad.

2022-01-13 11:55 UTC, k7per commented on koncept/appendix-mattenheter.tex
> +tekniska begrepp.  Märk att samma symboler används olika inom olika
Gjort. Kan du kolla att det blev som du vill?

2022-01-15 15:01 UTC, SM7NTJ approved these changes
Det finns en skillnad i hur koncept.pdf byggs av de olika programmen som medför att bilderna får lite olika placering i förhållande till texten.
Jag har nu kikat på bygget koncept.2.5.0-pre+b1692541121.453eee7 som jag tankade ner från actions #585.
Skillnaden i bildplacering är kvar främst i avsnitt 5. Jag tycker dock att helheten verkar ok och att vi i nuläget kan acceptera detta.

När det gäller ny mening på ny rad är det något vi införde och började använde när vi skriver ny text.
Vi försöker då se till att alla nya meningar påbörjas på ny rad.
Det underlättar bland annat senare redigering.

2022-01-15 19:15 UTC, phieri commented on koncept/appendix-mattenheter.tex
> +tekniska begrepp.  Märk att samma symboler används olika inom olika
Ja! Tack!

2022-01-15 20:12 UTC, phieri approved these changes

2022-01-18 18:28 UTC, merged