Mixed issues
SverigesSandareamatorer/SSA-Akademin pull request #588
Opened 2022-01-18 20:27 UTC by k7per

### Innehåll

- Förändringar

### Checklista

- [ ] Följer stilmallen specificerad i [`CONTRIBUTING.md`](../blob/master/.github/CONTRIBUTING.md)
- [ ] Språkligt granskad (stavning och grammatik)
- [ ] Förändringar bygger utan fel lokalt
- [ ] Förändringar bygger utan fel på byggserver
- [ ] Förändringar (om signifikanta) införd i [`CHANGELOG.md`](../blob/master/CHANGELOG.md)
- [ ] Godkänd av två granskare
- [ ] Författaren är klar och godkänner merge

### Stänger följande issues

Fixes # `<- följt av issue-nummer`
#568 #550

2022-01-19 20:25 UTC, SM7NTJ approved these changes

2022-01-19 21:29 UTC, sm5phu requested changes
Passa på och ändra mellanstadiespråket "upplänks-frekvens" och "nedlänks-frekvens" till vuxenvarienterna "upplänksfrekvens" respektive "nedlänksfrekvens".

2022-01-20 11:36 UTC, k7per commented
Ned eller ner?

per


On Wed, Jan 19, 2022 at 10:29 PM sm5phu ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Passa på och ändra mellanstadiespråket "upplänks-frekvens" och
> "nedlänks-frekvens" till vuxenvarienterna "upplänksfrekvens" respektive
> "nedlänksfrekvens".
>
> —
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F588%23pullrequestreview-857382255&data=04%7C01%7C%7C3f757318a60c4e451a0308d9db92cba2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637782245789300646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ey3sq6uXQHhSzHmuTAMrZz%2BWBPUebJnO98WTJx7phNY%3D&reserved=0>,
> or unsubscribe
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWOAPQC7RST7MZLJQM6FVR3UW4UMBANCNFSM5MIEAHGA&data=04%7C01%7C%7C3f757318a60c4e451a0308d9db92cba2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637782245789300646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YSdJE3E9i82yFASbyl8cc%2B1FZxXR0I9RGKCrtE%2BZJak%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2022-01-20 13:15 UTC, sm5phu commented
"ner" eller "ned" verkar vara hugget som stucket. "Nedlänk" ger något fler googleträffar. Men OK att behålla "ner".

2022-01-20 15:18 UTC, k7per commented
Klart.

On Thu, Jan 20, 2022 at 2:15 PM sm5phu ***@***.***> wrote:

> "ner" eller "ned" verkar vara hugget som stucket. "Nedlänk" ger något fler
> googleträffar. Men OK att behålla "ner".
>
> —
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverigesSandareamatorer%2FSSA-Akademin%2Fpull%2F588%23issuecomment-1017494329&data=04%7C01%7C%7Cf469dc191143447cfcc708d9dc16f433%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637782813415206218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6I6n1uNg96ihch9dkpod1vK2eaezfzAWAW6vmNrpMS0%3D&reserved=0>,
> or unsubscribe
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWOAPQAXOI7OD64GIOZB62LUXADHVANCNFSM5MIEAHGA&data=04%7C01%7C%7Cf469dc191143447cfcc708d9dc16f433%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637782813415206218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F127XdmJCm0lfQwWOAuTo1q98gqNCgg2ghVsbAp5upA%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-21 21:01 UTC, sm5phu approved these changes

2022-01-26 18:09 UTC, merged