Blandat 21/11 -22
SverigesSandareamatorer/SSA-Akademin pull request #622
Opened 2022-11-21 17:13 UTC by phieri

### Innehåll

- Skriver tydligare ut vilken version av TeX Live som byggservern använder m.m.
- Fix #599 

### Checklista

- [x] Följer stilmallen specificerad i [CONTRIBUTING.md](../blob/master/.github/CONTRIBUTING.md)
- [ ] Språkligt granskad (stavning och grammatik)
- [ ] Förändringar bygger utan fel lokalt
- [x] Förändringar bygger utan fel på byggserver
- [x] Förändringar (om signifikanta) införd i [CHANGELOG.md](../blob/master/CHANGELOG.md)
- [ ] Godkänd av två granskare
- [x] Författaren är klar och godkänner merge

2022-11-21 17:32 UTC, SM7NTJ approved these changes

2022-11-23 21:48 UTC, sm5phu approved these changes

2022-11-24 05:07 UTC, SM7NTJ requested changes
5,3 MHz är numera ett amatörradioband
Vi behöver därför ändra rad 49 i appendix-iaru-bandplan och ta bort den fetstilade texten
textbf{Är inte ett amatörband i Sverige}
PTSFS 2020:5 29 § 5,3515–5,3665 MHz: Radiosändare för amatörradiotrafik
Vi behöver även ändra appendix N och lägga till bandet där. Jag lägger det som en issue

2022-11-25 04:58 UTC, SM7NTJ approved these changes

2022-11-25 23:38 UTC, merged