Ersatt fyra bilder i kapitel två med hjälp av circuitikz
SverigesSandareamatorer/SSA-Akademin pull request #696
Opened 2024-01-21 12:58 UTC by SM7NTJ

bilderna 2.16 2.17 2.18 och 2.23 har ersatts med kodade figurer

## Innehåll

- Förändringar

## Checklista

- [ ] Följer stilmallen specificerad i [CONTRIBUTING.md](../.github/CONTRIBUTING.md)
- [ ] Bygger utan fel lokalt
- [ ] Bygger utan fel på byggserver
- [ ] Signifikanta förändringar införda i [CHANGELOG.md](../CHANGELOG.md)
- [ ] Författaren är klar och godkänner sammanfogning
- [ ] Språkligt granskad (stavning och grammatik)
- [ ] Godkänd av två granskare

## Stänger följande issues

Fixes # `<- följt av issue-nummer`

2024-01-21 13:00 UTC, SM7NTJ commented
Fixes #646 #680

2024-01-21 22:14 UTC, phieri requested changes

2024-01-21 22:14 UTC, phieri commented on koncept/chapter2-6.tex
> +	\begin{circuitikz}[american,]
Jag hittar inte att `american` skulle ha någon påverkan på transistorer. Ta bort, eller ta bort åtminstone kommatecknen. Gäller även rad 176.

2024-01-22 07:58 UTC, SM7NTJ commented on koncept/chapter2-6.tex
> +	\begin{circuitikz}[american,]
Fixat.
Tar nog ett tag innan man lärt sig alla varianter och hur de används ;=)

2024-01-22 19:00 UTC, phieri approved these changes

2024-01-31 18:45 UTC, sm5phu approved these changes

2024-01-31 18:45 UTC, merged