Flyttat hembyggd radiosändare till EMC
SverigesSandareamatorer/SSA-Akademin pull request #703
Opened 2024-02-05 16:47 UTC by SM7NTJ

Flyttat skrivningen om hembyggd radiosändare och radioutrustningslagen från elsäkerhet till avsnittet om EMC

## Innehåll

- Förändringar

## Checklista

- [ ] Följer stilmallen specificerad i [CONTRIBUTING.md](../.github/CONTRIBUTING.md)
- [ ] Bygger utan fel lokalt
- [ ] Bygger utan fel på byggserver
- [ ] Signifikanta förändringar införda i [CHANGELOG.md](../CHANGELOG.md)
- [ ] Författaren är klar och godkänner sammanfogning
- [ ] Språkligt granskad (stavning och grammatik)
- [ ] Godkänd av två granskare

## Stänger följande issues

Fixes # `<- följt av issue-nummer`
Fixes #591

2024-02-05 16:58 UTC, SM7NTJ commented
Kommer inte åt att ändra changelog
- Flyttat skrivningen om hembyggd radiosändare till avsnittet om EMC

2024-02-05 19:07 UTC, phieri commented
Jag la till texten i CHANGELOG.md.

2024-02-05 19:15 UTC, phieri requested changes

2024-02-05 19:15 UTC, phieri commented on koncept/chapter10-1.tex
> +\label{hembyggd radiosändare}
Använd endast ASCII-tecken (men inte heller understreck) i \label{}. Det är en av sakerna som gör att EPUB inte går att bygga just nu.

2024-02-05 19:15 UTC, phieri commented on koncept/chapter12-2.tex
> +\label{praktiska råd för självbyggaren}
Använd inte ÅÄÖ i \label{}.

2024-02-05 21:55 UTC, sm5phu commented
Texten i 10.1.3 säger att jag får inte "montera avstörningsfilter inuti en CE-märkt apparat". 
Jag förstår att det där syftar på konsumentelektronik som inte är relaterad till amatörradio, exempelvis grannens TV.

Men formuleringen kan misstolkas, och då kommer säkert någon att misstolka den. 
Någon kommer att få för sig att alla modifieringar av CE-märkta sändare för användning inom amatörbanden är tillåtna, UTOM att montera ett avstörningsfilter inuti apparaten.

2024-02-06 08:23 UTC, SM7NTJ commented
Plockat bort texten i 10.1.3 om att du inte får "montera avstörningsfilter inuti en CE-märkt apparat".
Flödat om bilder för att minska de tomma vita ytor som bildades när texten om hembyggd radiosändare flyttades hit.
Misslyckats att få bilden10:14 nycklingsfilter i 10.4 på rätt ställe. Den hamnar på en egen sida då det inte verkar finnas något bildkommando som placerar den nertill på sidan

2024-02-06 11:40 UTC, SM7NTJ commented
Skapat \smallbotfigtwo som nytt figure macro i koncept.tex Det har växeln bht och gör att bild 10:14 kan placeras sist i spalt.
Den ensamma bilden försvinner från sidan tillsammans med den helt tomma följande sidan.

2024-02-13 16:46 UTC, sm5phu approved these changes

2024-02-13 18:16 UTC, merged